services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Exposes port 80 in the container to port 80 on your host machine
    volumes:
      - .:/var/www/html:cached  # Maps your project folder to the container with optimized sync
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    depends_on:
      - db  # Ensures the database service is started before the app service

  db:
    image: mysql:5.7  # Using MySQL version 5.7; adjust if needed
    platform: linux/amd64  # Specify architecture to use emulation
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Set a strong root password
      MYSQL_DATABASE: pixelium  # Name of the initial database
      MYSQL_USER: codeigniter_user  # Create a specific user for CodeIgniter
      MYSQL_PASSWORD: codeigniter_password  # Password for the specific user
    ports:
      - "3306:3306"  # Expose MySQL's default port
    volumes:
      - db_data:/var/lib/mysql  # Store MySQL data outside of the container
      - ./db:/docker-entrypoint-initdb.d
    restart: always

volumes:
  db_data:  # Named volume to persist database data
